model: "openai/gpt-oss-120b"
project: "faktura_classifier_gpt"
data: "/Users/alhu/Data/Large_Faktura/Faktura20232024.xlsx"
output: "/Users/alhu/Data/Large_Faktura/Fakturaklassificering_GPT_OSS_120.parquet"
backup_itr: 10

data_params:
  kreditor: "Kreditor"
  fakturanummer: "Fakturanummer"
  linjenummer: "Linjenummer"
  input_col: "Fakturabeskrivelse"
  antal: "Antal"
  stykpris: "Stykpris"

others:
  webhook_url: https://discord.com/api/webhooks/1382423391851511858/tKGJMIG1TpUDGjdLFcQlvz6cauWfPZbpUC9XUssbjGwAg_YDPLg0i7849l7ZwBlAmXkn
  webhook_itr: 500


  # model, project, data, output, [backup_itr, data_params, model_params]. For data_params there should be a default for input and output.