model: "meta-llama-3.1-8b-instruct"
project: "faktura_advanced"
data: "/Users/alexander/VSC_Work/llm-pipelines/data/Fakturalinjer_Sample.xlsx"
output: "/Users/alexander/På min Mac/Data/Varelinjer_Test.xlsx"
backup_itr: 100

data_params:
  kreditor: "Kreditor"
  fakturanummer: "Fakturanummer"
  linjenummer: "Linjenummer"
  input_col: "Fakturabeskrivelse"
  antal: "Antal"
  stykpris: "Stykpris"

model_params:
  max_tokens: 1500
  temperature: 0.7

others:
  webhook_url: https://discord.com/api/webhooks/1382423391851511858/tKGJMIG1TpUDGjdLFcQlvz6cauWfPZbpUC9XUssbjGwAg_YDPLg0i7849l7ZwBlAmXkn
  webhook_itr: 5


  # model, project, data, output, [backup_itr, data_params, model_params]. For data_params there should be a default for input and output.