model: "qwen/qwen3-235b-a22b"
project: "faktura_effective"
data: "/Users/alhu/Data/Indkøbsdata/Indkøbsdata_Parquet/Varelinjer_2020_2024_FINAL.parquet"
data_fakturaer: "/Users/alhu/Data/Indkøbsdata/Indkøbsdata_Parquet/Fakturalinjer_2020_2024.parquet"
output: "/Users/alhu/Data/Indkøbsdata/Output/Varelinjer_Klassificeret.parquet"
backup_itr: 25

data_params:
  kreditor: "Kreditor"
  input_col: "Fakturabeskrivelse"

data_params_fakturaer:
  kreditor: "Kreditor"
  fakturabeskrivelse: "Fakturabeskrivelse"
  antal: "Antal"
  stykpris: "Stykpris"
  linjenummer: "Linjenummer"
  fakturanummer: "Fakturanummer"

model_params:
  max_tokens: 4500
  temperature: 0.7

others:
  webhook_url: https://discord.com/api/webhooks/1388150970667634798/hs-Nr9Q1VJGXjIsrnuH1gjzXo2MzrEomYL5xe1IrAdHnwRZiUkfqE3uGYmNhuhi5vlay
  webhook_itr: 1000


  # model, project, data, output, [backup_itr, data_params, model_params]. For data_params there should be a default for input and output.