model: "qwen3-235b-a22b-instruct-2507"
project: "køn_genkender"
data: "/Users/alhu/Downloads/AktiveFælles Data.xlsx"
output: "/Users/alhu/Downloads/AktiveFælles_Data_Done2.xlsx"
backup_itr: 10

model_params:
  max_tokens: 4500
  temperature: 0.7

  # model, project, data, output, [backup_itr, data_params, model_params]. For data_params there should be a default for input and output.