model: "phi-4"
project: "simple_indkob"
data: "/Users/alhu/Data/Testdata_Varelinjer/Varelinjer_S.xlsx"
output: "/Users/alhu/Data/Simple_Faktura_Test/Varelinjer_Sample_Output_Test6.xlsx"
backup_itr: 1

data_params:
  input_col: "Fakturabeskrivelse"

model_params:
  max_tokens: 200
  temperature: 0.3


  # model, project, data, output, [backup_itr, data_params, model_params]. For data_params there should be a default for input and output.