model: "tess-3-mistral-large-2-123b"
data: "/Users/alhu/Data/Varelinjer_Sample_S.xlsx"
output: "/Users/alhu/Data/Varelinjer_Sample_Output_Test5.xlsx"
backup: null
backup_itr: null
log: "../logs/simple_indkob"

data_params:
  input_col: "Fakturabeskrivelse"

model_params:
  max_tokens: 200
  temperature: 0.3